spring.application.name=FLearn_SpringBoot
server.port=8080

# Cấu hình kết nối SQL Server (Thay đổi tài khoản sa nếu cần)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FLearnDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Vì đã chạy script SQL tạo bảng trước đó, chọn "validate" để kiểm tra cấu trúc thay vì tạo đè
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect

# Tắt cache Thymeleaf để khi sửa giao diện không cần restart lại server
spring.thymeleaf.cache=false
# 1. Tắt đổi tên của Spring Boot
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# 2. Ép buộc Hibernate 6 giữ nguyên tên cột (Bảo hiểm lớp 2)
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# Cấu hình Spring Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minhtuan2k5vp@gmail.com
spring.mail.password=sbvsrhhnyliqnexn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true